name: Build/release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        BUILD_TARGET: [release] # refers to a cargo profile

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-directories: cli/target
          cache-targets: cli

      - name: Build and test
        working-directory: cli
        run: |
          cargo build --profile ${{ matrix.BUILD_TARGET }}
          cargo test --profile ${{ matrix.BUILD_TARGET }}
          cargo clippy --profile ${{ matrix.BUILD_TARGET }}
